---
sources:
  overview-server:
    url: https://github.com/overview/overview-server.git
    artifact_bucket: overview-builds
    build_remotely: true
    build_commands:
      - ./build archive.zip

machine_types:
  conglomerate:
    start_commands:
      - sudo /opt/overview/prepare-frontend.sh
      - sudo /opt/overview/prepare-worker.sh
      - sudo systemctl start overview-frontend overview-worker

    stop_commands:
      - sudo systemctl stop overview-frontend overview-worker

    restart_commands:
      - sudo /opt/overview/prepare-frontend.sh
      - sudo /opt/overview/prepare-worker.sh
      - sudo systemctl restart overview-frontend overview-worker

remote_build:
  availability_zone: us-east-1a
  security_group_id: sg-cb1d97ac
  instance_type: r3.large
  vpc_id: vpc-5c3fd138
  subnet_id: subnet-1e134747
  ami_id: ami-fd256898 # https://cloud-images.ubuntu.com/releases/15.04/release/ - 64-bit, hvm-ssd
  cache_volume_id: vol-998c9fdb
  keypair_name: manage
  user_data: |
    #cloud-config
    hostname: build
    repo_update: true
    repo_upgrade: all
    packages:
      - build-essential
      - nodejs
      - nodejs-dev
      - nodejs-legacy
      - npm
      - openjdk-8-jdk
      - ca-certificates-java
      - zip
    runcmd:
      - env DEBIAN_FRONTEND=noninteractive apt-get -qq -y remove --purge openjdk-7-jre openjdk-7-jre-headless # ca-certificates-java puts it there in an apt-dependency vortex of uselessness
      - /var/lib/dpkg/info/ca-certificates-java.postinst configure # https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1396760
      - echo "127.0.1.1 $(hostname)" | tee -a /etc/hosts
  init_commands:
    - mkdir -p build-cache && sudo mount /dev/xvdg build-cache && ln -sf `pwd`/build-cache/.ivy2 . && ln -sf `pwd`/build-cache/.npm . && ln -sf `pwd`/build-cache/.sbt .
    - mkdir -p build && sudo mkfs.ext2 -q /dev/xvdf && sudo mount /dev/xvdf build && sudo chown ubuntu:ubuntu build
