---
sources:
  overview-server:
    url: https://github.com/overview/overview-server.git
    artifact_bucket: overview-builds
    build_remotely: true
    build_commands:
      - ./build archive.zip

machine_types:
  web:
    start_commands:
      - sudo start overview-frontend

    stop_commands:
      - sudo stop overview-frontend

    restart_commands:
      - sudo stop overview-frontend
      - sleep 2
      - sudo start overview-frontend

  worker:
    start_commands:
      - sudo start overview-worker
      - sudo start overview-documentset-worker

    stop:
      - sudo stop overview-worker
      - sudo stop overview-documentset-worker

    restart_commands:
      - sudo stop overview-worker
      - sudo stop overview-documentset-worker
      - sleep 2
      - sudo start overview-worker
      - sudo start overview-documentset-worker
  database: {}
  searchindex: {}

remote_build:
  availability_zone: us-east-1a
  security_group: build
  instance_type: c3.large
  ami_id: ami-ee793a86 # https://cloud-images.ubuntu.com/releases/14.10/release/ - 64-bit, hvm-ssd
  cache_volume_id: vol-998c9fdb
  keypair_name: manage
  init_commands:
    - sudo apt-get -q update >/dev/null # -qq prevents update from working
    - sudo env DEBIAN_FRONTEND=noninteractive apt-get -qq -y dist-upgrade >/dev/null # -qq doesn't mute stuff
    - sudo apt-get -q update >/dev/null # no idea why we need this again, but we do
    - sudo env DEBIAN_FRONTEND=noninteractive apt-get -qq -y install build-essential nodejs nodejs-dev nodejs-legacy npm openjdk-8-jdk zip ca-certificates-java >/dev/null
    - mkdir -p build-cache && sudo mount /dev/xvdg build-cache && ln -sf `pwd`/build-cache/.ivy2 . && ln -sf `pwd`/build-cache/.npm . && ln -sf `pwd`/build-cache/.sbt .
    - sudo umount /dev/xvde && sudo mkswap -f /dev/xvde && sudo swapon /dev/xvde
    - mkdir -p build && sudo mkfs.ext2 -q /dev/xvdf && sudo mount /dev/xvdf build && sudo chown ubuntu:ubuntu build
