---
sources:
  overview-server:
    url: https://github.com/overview/overview-server.git
    build_remotely: true
    build_commands:
      - ./build archive.zip

  aws-overview-config:
    url: https://github.com/overview/aws-overview-config.git
    build_commands:
      - OVERVIEW_CONFIG=/opt/overview/config/manage/config.yml OVERVIEW_SECRETS=/opt/overview/config/manage/secrets.yml ./generate.sh
      - "(cd generated && zip -r ../archive.zip *)"

build_overview_server_component: &build_overview_server_component
  source: overview-server
  prepare_commands:
    - "(cd source/libs && xargs -I '{}' -a ../<%= component.name %>/classpath.txt cp '{}' ../../component)"

build_config_component: &build_config_component
  source: aws-overview-config
  prepare_commands:
    - "cp -a source/<%= environment %>/<%= component.name[7..-1] %>/* component"
  deploy_commands:
    - "sudo cp -a <%= component.installed_path %>/root/* /"
    - "<%= component.installed_path %>/scripts/start.sh"

components:
  frontend:
    <<: *build_overview_server_component
    deploy_commands:
      - /opt/overview/config-web/scripts/start.sh
  worker:
    <<: *build_overview_server_component
    deploy_commands:
      - /opt/overview/config-worker/scripts/start.sh
  documentset-worker:
    <<: *build_overview_server_component
    deploy_commands:
      - /opt/overview/config-worker/scripts/start.sh
  message-broker:
    <<: *build_overview_server_component
    deploy_commands:
      - /opt/overview/config-worker/scripts/start.sh
  search-index:
    <<: *build_overview_server_component
    deploy_commands:
      - /opt/overview/config-searchindex/scripts/start.sh

  config-web:
    <<: *build_config_component
  config-worker:
    <<: *build_config_component
  config-database:
    <<: *build_config_component
  config-searchindex:
    <<: *build_config_component

machine_types:
  web:
    components:
      - config-web
      - frontend

  worker:
    components:
      - config-worker
      - worker
      - documentset-worker
      - message-broker

  search-index:
    components:
      - search-index
      - config-searchindex

  database:
    components:
      - config-database
