---
sources:
  overview-server:
    url: https://github.com/overview/overview-server.git
    build_remotely: true
    build_commands:
      - ./build archive.zip

  aws-overview-config:
    url: https://github.com/overview/aws-overview-config.git
    build_env:
      OVERVIEW_SECRETS: /opt/overview/config/manage/secrets.yml
      OVERVIEW_CONFIG: /opt/overview/config/manage/config.yml
    build_commands:
      - OVERVIEW_CONFIG=/opt/overview/config/manage/config.yml OVERVIEW_SECRETS=/opt/overview/config/manage/secrets.yml ./generate.sh
      - zip -r archive.zip generated

build_overview_server_component: &build_overview_server_component
  source: overview-server
  build_commands:
    - "unzip #{source_artifact.archive_zip}"
    - "cd archive/lib"
    - "xargs -I '{}' -a ../#{component.name}/classpath.txt ln '{}' #{component_artifact.contents_path}"

build_config_component: &build_config_component
  source: aws-overview-config
  build_commands:
    - "unzip #{source_artifact.archive_zip}"
    - "cd archive/generated"
    - "cp -a #{component.name[7..-1]}/* #{component_artifact.contents_path}"
  install_commands:
    - "cp -a #{component_artifact.path}/root/* /"
  post_install_commands:
    - "#{component_artifact.path}/scripts/start.sh"

components:
  frontend:
    <<: *build_overview_server_component
    post_install_commands:
      - /opt/overview/config-web/scripts/start.sh
  worker:
    <<: *build_overview_server_component
    post_install_commands:
      - /opt/overview/config-worker/scripts/start.sh
  documentset-worker:
    <<: *build_overview_server_component
    post_install_commands:
      - /opt/overview/config-worker/scripts/start.sh
  message-broker:
    <<: *build_overview_server_component
    post_install_commands:
      - /opt/overview/config-worker/scripts/start.sh
  search-index:
    <<: *build_overview_server_component
    post_install_commands:
      - /opt/overview/config-searchindex/scripts/start.sh

  config-web:
    <<: *build_config_component
  config-worker:
    <<: *build_config_component
  config-database:
    <<: *build_config_component
  config-searchindex:
    <<: *build_config_component
