---
sources:
  overview-server:
    url: https://github.com/overview/overview-server.git
    artifact_bucket: overview-builds.overviewdocs.com

machine_types:
  logstash:
    start_commands: []
    stop_commands: []
    restart_commands: []

  conglomerate:
    start_commands:
      - sudo /opt/overview/prepare-web.sh
      - sudo /opt/overview/prepare-worker.sh
      - sudo systemctl start overview-web overview-worker

    stop_commands:
      - sudo systemctl stop overview-web overview-worker

    restart_commands:
      - sudo /opt/overview/prepare-web.sh
      - sudo /opt/overview/prepare-worker.sh
      - sudo systemctl restart overview-web overview-worker
