---
managed_code_path: /opt/overview/managed-code
projects:
  main:
    url: git@github.com:overview/overview-server.git
    build_command: './sbt dist'
    clean_command: './sbt all/clean'
    export_command: 'unzip -q -j dist/overview*.zip "*.jar" -d #{DESTINATION_PATH}'
    copy:
      web: ''
  worker:
    url: git@github.com:overview/overview-server.git
    build_command: './sbt worker/simple-dist'
    clean_command: './sbt all/clean'
    export_command: 'unzip -q -j worker/dist/worker*.zip "*.jar" -d #{DESTINATION_PATH}'
    copy: 
      worker: ''
  documentset-worker:
    url: git@github.com:overview/overview-server.git
    build_command: './sbt documentset-worker/simple-dist'
    clean_command: './sbt all/clean'
    export_command: 'unzip -q -j documentset-worker/dist/documentset-worker*.zip "*.jar" -d #{DESTINATION_PATH}'
    copy: 
      worker: ''
  message-broker:
    url: git@github.com:overview/overview-server.git
    build_command: './sbt message-broker/simple-dist'
    clean_command: './sbt message-broker/clean'
    export_command: 'unzip -q -j message-broker/dist/message-broker*.zip "*.jar" -d #{DESTINATION_PATH}'
    copy: 
      worker: ''
  search-index:
    url: git@github.com:overview/overview-server.git
    build_command: './sbt search-index/simple-dist'
    clean_command: './sbt search-index/clean'
    export_command: 'unzip -q -j search-index/dist/search-index*.zip "*.jar" -d #{DESTINATION_PATH}'
    copy: 
      searchindex: ''
  config:
    url: git@github.com:overview/aws-overview-config.git
    build_command: '/opt/overview/managed-code/config/repo/generate.sh'
    clean_command: 'rm -rv generated/'
    build_env:
      OVERVIEW_SECRETS: /opt/overview/config/manage/secrets.yml
      OVERVIEW_CONFIG: /opt/overview/config/manage/config.yml
    export_command: 'cp -a generated/* #{DESTINATION_PATH}'
    copy:
      web: '#{ENV}/web'
      worker: '#{ENV}/worker'
      database: '#{ENV}/database'
      searchindex: '#{ENV}/searchindex'


  
repositories:
  main:
    url: git@github.com:overview/overview-server.git
    build_command: './sbt all/dist all/simple-dist'
    clean_command: './sbt all/clean'
    # unzip args: "-j" junk paths for flat output dir; "-d" destination directory; "-q" quiet
    export_command: 'unzip -q -j dist/overview*.zip "*.jar" -d #{DESTINATION_PATH}'
    copy:
      web: ''
      worker: ''
  config:
    url: git@github.com:overview/aws-overview-config.git
    build_command: '/opt/overview/managed-code/config/repo/generate.sh'
    clean_command: 'rm -rv generated/'
    build_env:
      OVERVIEW_SECRETS: /opt/overview/config/manage/secrets.yml
      OVERVIEW_CONFIG: /opt/overview/config/manage/config.yml
    export_command: 'cp -a generated/* #{DESTINATION_PATH}'
    copy:
      web: '#{ENV}/web'
      worker: '#{ENV}/worker'
      database: '#{ENV}/database'
