---
sources:
  overview-server:
    url: https://github.com/overview/overview-server.git
    build_remotely: true
    build_commands:
      - ./build archive.zip

  aws-overview-config:
    url: https://github.com/overview/aws-overview-config.git
    build_commands:
      - bundle install --deployment
      - env OVERVIEW_CONFIG=/opt/overview/config/manage/config.yml OVERVIEW_SECRETS=/opt/overview/config/manage/secrets.yml ./generate.sh
      - "(cd generated && zip -r ../archive.zip *)"

build_overview_server_component: &build_overview_server_component
  source: overview-server
  prepare_commands:
    - "(cd source/archive/lib && xargs -I '{}' -a ../<%= component.name %>/classpath.txt cp '{}' ../../../component)"

build_config_component: &build_config_component
  source: aws-overview-config
  prepare_commands:
    - "cp -a source/<%= environment %>/<%= component.name[7..-1] %>/* component"
  deploy_commands:
    - "sudo cp -a <%= component.install_path %>/root/* /"
    - "sh <%= component.install_path %>/scripts/start.sh"

components:
  frontend:
    <<: *build_overview_server_component
    deploy_commands:
      - sh /opt/overview/config-web/scripts/start.sh
  worker:
    <<: *build_overview_server_component
    deploy_commands:
      - sh /opt/overview/config-worker/scripts/start.sh
  documentset-worker:
    <<: *build_overview_server_component
    deploy_commands:
      - sh /opt/overview/config-worker/scripts/start.sh
  message-broker:
    <<: *build_overview_server_component
    deploy_commands:
      - sh /opt/overview/config-searchindex/scripts/start.sh
  search-index:
    <<: *build_overview_server_component
    deploy_commands:
      - sh /opt/overview/config-searchindex/scripts/start.sh

  config-common:
    <<: *build_config_component
  config-web:
    <<: *build_config_component
  config-worker:
    <<: *build_config_component
  config-database:
    <<: *build_config_component
  config-searchindex:
    <<: *build_config_component

machine_types:
  web:
    components:
      - config-common
      - config-web
      - frontend

  worker:
    components:
      - config-common
      - config-worker
      - worker
      - documentset-worker

  searchindex:
    components:
      - search-index
      - message-broker
      - config-common
      - config-searchindex

  database:
    components:
      - config-common
      - config-database

  logstash:
    components:
      - config-common

remote_build:
  availability_zone: us-east-1a
  security_group: build
  instance_type: c3.large
  ami_id: ami-c212afaa
  cache_volume_id: vol-998c9fdb
  keypair_name: manage
