---
sources:
  overview-server:
    url: https://github.com/overview/overview-server.git
    artifact_bucket: overview-builds
    build_remotely: true
    build_commands:
      - ./build archive.zip

machine_types:
  web:
    start_commands:
      - sudo start overview-frontend

    stop_commands:
      - sudo stop overview-frontend

    restart_commands:
      - sudo stop overview-frontend
      - sleep 2
      - sudo start overview-frontend

  worker:
    start_commands:
      - sudo start overview-worker
      - sudo start overview-documentset-worker

    stop:
      - sudo stop overview-worker
      - sudo stop overview-documentset-worker

    restart_commands:
      - sudo stop overview-worker
      - sudo stop overview-documentset-worker
      - sleep 2
      - sudo start overview-worker
      - sudo start overview-documentset-worker
  database: {}
  searchindex: {}

remote_build:
  availability_zone: us-east-1a
  security_group: build
  instance_type: c3.large
  ami_id: ami-c212afaa
  cache_volume_id: vol-998c9fdb
  keypair_name: manage
