---
sources:
  overview-server:
    url: https://github.com/overview/overview-server.git
    artifact_bucket: overview-builds
    build_remotely: true
    build_commands:
      - ./build archive.zip

machine_types:
  web:
    start_commands:
      - sudo /opt/overview/prepare-frontend.sh
      - sudo systemctl start overview-frontend

    stop_commands:
      - sudo systemctl stop overview-frontend

    restart_commands:
      - sudo /opt/overview/prepare-frontend.sh
      - sudo systemctl restart overview-frontend

  worker:
    start_commands:
      - sudo /opt/overview/prepare-worker.sh documentset-worker
      - sudo /opt/overview/prepare-worker.sh worker
      - sudo systemctl start overview-worker overview-documentset-worker

    stop:
      - sudo systemctl stop overview-worker overview-documentset-worker

    restart_commands:
      - sudo /opt/overview/prepare-worker.sh documentset-worker
      - sudo /opt/overview/prepare-worker.sh worker
      - sudo systemctl restart overview-worker overview-documentset-worker
  database: {}
  searchindex: {}

remote_build:
  availability_zone: us-east-1a
  security_group_id: sg-cb1d97ac
  instance_type: r3.large
  vpc_id: vpc-5c3fd138
  subnet_id: subnet-1e134747
  ami_id: ami-ee793a86 # https://cloud-images.ubuntu.com/releases/14.10/release/ - 64-bit, hvm-ssd
  cache_volume_id: vol-998c9fdb
  keypair_name: manage
  user_data: |
    #cloud-config
    hostname: build
    repo_update: true
    repo_upgrade: all
    packages:
      - build-essential
      - nodejs
      - nodejs-dev
      - nodejs-legacy
      - npm
      - openjdk-8-jdk
      - zip
      - ca-certificates-java
  init_commands:
    - sudo env DEBIAN_FRONTEND=noninteractive apt-get -qq -y remove --purge openjdk-7-jre openjdk-7-jre-headless # ca-certificates-java puts it there in an apt-dependency vortex of uselessness
    - mkdir -p build-cache && sudo mount /dev/xvdg build-cache && ln -sf `pwd`/build-cache/.ivy2 . && ln -sf `pwd`/build-cache/.npm . && ln -sf `pwd`/build-cache/.sbt .
    - mkdir -p build && sudo mkfs.ext2 -q /dev/xvdf && sudo mount /dev/xvdf build && sudo chown ubuntu:ubuntu build
