source 'https://rubygems.org'

gem 'git'
gem 'net-ssh'
gem 'net-scp'
gem 'posix-spawn'

group :test do
  gem 'rspec', '~> 3.0.0.beta2'
end

group :development do
  gem 'debugger'
  gem 'guard-rspec', require: false
end
